development:
  adapter: postgresql
  encoding: unicode
  database: prometheus_development
  pool: 5
  host: localhost
  username: chyld
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: prometheus_test
  pool: 5
  host: localhost
  username: chyld
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: prometheus_production
  pool: 5
  host: localhost
  username: chyld
  password:
